include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false

analyzer:
  errors:
    # freezed를 json_serializable과 함께 사용할 경우
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
